### ISSUE TITLE
Include NSTimer in block?

### ISSUE THREAD

**Issue by efremidze** [radex/SwiftyTimer#18]
What are your thoughts about including the timer object in the block?
```
public class func every(interval: NSTimeInterval, _ block: NSTimer -> Void) -> NSTimer {}
```
Otherwise I need to declare the variable separately like this:
```
var timer: NSTimer?
timer = NSTimer.every(5.seconds) {
    timer?.invalidate()
}
```

**Comment by radex** [comment]
@efremidze Hey, I'm not against this, but I don't want the passed timer object to be **required**. Often times, I really don't care about it, because I'm going to assign it to a property anyway.

Take a look at #8. Last time someone took a look at it, there was no way to have both without errors about ambiguity.

But that was a while ago. If you can make both:

~~~
NSTimer.every(5.seconds) {
     // whatever
}
~~~

and

~~~
NSTimer.every(5.seconds) { timer in
     // whatever
}
~~~

work, I'd accept such a PR in an instant.

**Comment by efremidze** [comment]
That currently a limitation in Swift. Let wait until Swift 3. :smiley:

**Comment by radex** [comment]
You could help by filing a bug on bugs.swift.org :)

**Comment by efremidze** [comment]
good idea :+1:

**Comment by radex** [comment]
I'll keep it open in case someone is looking for this ;)

**Comment by radex** [comment]
Added on master. Unfortunately if you want the timer passed in, you have to say `{ (timer: NSTimer} in ... }`, but hey, it works!

**Comment by efremidze** [comment]
👍
